### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by odidev** [mwarkentin/django-watchman#172]
I followed the GitHub Action and working on installing and testing django-watchman package for amd64 and arm64 architectures. While testing this package using “pytest”, I am getting `ImportError: No module named 'watchman'` error. After installing watchman using the command `pip install watchman` getting another error as `ImportError: No module named 'watchman.settings'` for both architectures.  

It would be really helpful if you could share some pointers on it  

**Log for reference:** https://github.com/odidev/django-watchman/runs/4581744472?check_suite_focus=true#step:6:70

**Comment by mwarkentin** [comment]
@odidev I haven't had a chance to finish the work to migrate the watchman tests from TravisCI to GitHub Actions unfortunately, so things are a bit broken right now. If you manage to get it working a PR would be very appreciated, otherwise I can let you know via this issue when I've got it working.

See also https://github.com/mwarkentin/django-watchman/issues/165

**Comment by mwarkentin** [comment]
@odidev I got GitHub Actions testing working in https://github.com/mwarkentin/django-watchman/pull/174

Can you pull the latest from `main` and see if that's working for you now?
