### ISSUE TITLE
Customize HTTP status code on failed checks

### ISSUE THREAD

**Issue by mwarkentin** [mwarkentin/django-watchman#43]
> The biggest problem we hit dealt with the inability to change the HTTP status codes on specific failed checks.

> For example, when some checks fail, we also want the status code returned by django-watchman to be a non HTTP 200. That allows something like Amazon's Elastic Load Balancer to mark the failing node for replacement.

**Comment by kilbasar** [comment]
See my pull request (#46). It adds a setting to return code 500 if any check is failed.

This lacks granularity (you can't specify which checks trigger a 500, they all do), but since the LB/whatever can specify which checks it wants to run, I don't see that as an issue.

By the way, great work on the module, really helpful!

**Comment by mwarkentin** [comment]
Closed in #46.
