### ISSUE TITLE
Should not pin `django-jsonview` in setup.py

### ISSUE THREAD

**Issue by mwarkentin** [mwarkentin/django-watchman#66]
https://github.com/mwarkentin/django-watchman/blob/master/setup.py#L40

Could be difficult to resolve conflicts - find some best practices for this somewhere, or just unpin?

**Comment by kezabelle** [comment]
Pinning specific versions is something I'd expect to see in `requirements.txt`, as it provides a known baseline from which things may be explored if problems arise. `setup.py` should use loose versions (unless there's a *strong* reason for pinning) so that users may benefit from dependency improvements/bugfixes/security releases without the dependee-package's intervention (in semver, by bumping a *patch* version & release just to update the dependency pin).

Pinning specific versions in the `setup.py` means that one day you may bump the dependency version to one that's incompatible with the version the user previously had their own dependencies on, which isn't fun for the user of your package.

WRT to resolving incompatibilities that arise, I wonder if the solution would be to introduce another travis/tox env which uses the latest release of every dependency (or grabs it directly from the main branch [ostensibly `master`] of each repo, as a tar.gz) and have that run when pushing to this package's repo.

**Comment by mwarkentin** [comment]
Thanks, that's definitely along the lines of what I was thinking.

**Comment by mwarkentin** [comment]
@kezabelle So I believe we needed the improved Django 1.8 compat in `django-jsonview#0.5.0` - would you recommend unpinning completely, or changing to `django-jsonview>=0.5.0`?

**Comment by kezabelle** [comment]
I'd suggest (personally) pinning to the minimum required version, on the basis that if a user has an old version already, and wants to add watchman, the watchman package would break without it's necessary version, and they won't know why; whereas at least if their code stops working as a result they'll hopefully know the code and understand why, and it's an edge case anyway (because one would hope the dependency package being upgraded didn't *routinely* change the API)

Very much "just my two cents" though, and I'd suggest confirming that notion by looking at the `setup.py` for other packages (taking the top ones from djangopackages seems like a fair idea)
