### ISSUE TITLE
Check celery / broker

### ISSUE THREAD

**Issue by mwarkentin** [mwarkentin/django-watchman#8]
- http://stackoverflow.com/questions/8506914/detect-whether-celery-is-available-running
- https://github.com/gpennington/django-ping/blob/develop/ping/checks.py#L89-L108

**Comment by mwarkentin** [comment]
@tisdall provided an example of a celery check he added in #77:

```python
def celery_worker_check():
    insp = inspect()
    d = insp.stats()
    if not d:
        raise Exception('No running celery workers were found')
    return {'ok': True}
```

**Comment by tisdall** [comment]
I derived it from the StackOverflow question above...  Make sure to include the `from celery.task.control import inspect`

**Comment by mwarkentin** [comment]
I'm going to close this as stale, but I still think it's a good idea. For checks which aren't configurable based on default Django settings, I'm leaning towards them being installed as separate "custom" packages (eg. `django-watchman-celery` which would have more knowledge about how the library is expected to be configured.

**Comment by tisdall** [comment]
Just an FYI on this...  I was looking at implementing AWS Route 53 Health Checks and this celery worker check seems to add almost a full second to the response time (the health check needs to respond within 2 seconds).

**Comment by tisdall** [comment]
also, newer versions of celery require something like
```python
from .celery import app  # the celery 'app' created in your project
insp = app.control.inspect()
d = insp.ping()  # was .stats(), but this works for a simple check
```

**Comment by tisdall** [comment]
Since this check is almost 1 second, it's not very practical.  I found a much much faster check is to have a really simple celery task and then call it as a check.

Here's my really simple task:

```python
@shared_task
def always_returns_three():
    """ Used to test that workers are responding """
    return 3
```

And my django-watchman check is this:

```python
    async_result = always_returns_three.delay()
    result = async_result.get(timeout=0.5)
    if result != 3:
        raise Exception('Celery return an unexpected result.')
```

So, if celery isn't responding than the check will timeout after half a second.  When it is working, though, it seems to respond in about 0.01 seconds.

**Comment by peterfarrell** [comment]
@tisdall Creating a task and expecting a result only tests if one worker is available. In a high availability environments, I would expect to have more than 1 worker available with a max that is horizontally scaled. Also, if your workers are backlogged with work (due to a surge), then the task may fail because it was queued because the using a test task is based on the premise that is will be processed immediately and not queued. I feel this approach of creating test tasks gives a false sense of security.

Using ping covers all these requirements where I have been burned on before using a test task as a means to check worker's being alive:

1. Expected minimum # of workers are alive
2. Do not rely on tasks returning immediately especially if workload is high and test task is queued.
3. Reduces the likelihood of false failures (too few workers, test tasks being queued, etc.)

You can set a timeout for `ping(timeout=0.5)` (defaults to 1 second). Using ping returns a list of all workers that respond alive. Therefore, you could then assert that at least X number of workers are alive.  I would suggest setting the timeout for ping to something lower than 1 second to improve the speed.

**Comment by tisdall** [comment]
@peterfarrell - The `ping` method example I gave above doesn't have a `timeout` arg, but the following does seem to work extremely fast:

```python
from .celery import app  # the celery 'app' created in your project
d = app.control.ping(timeout=0.1)
```

The issue is the `ping` doesn't know how many workers actually exists so it waits for the whole timeout and then sends all responses it received.  I'm guessing a better result would be to write a new method that immediately responds after it gets responses from all known workers (or reached the minimum like you described).

This seems to be effective and faster:
```python
from .celery import app  # the celery 'app' created in your project
minimum_workers = 5  # change this!
d = app.control.broadcast('ping', reply=True, timeout=0.5, limit=minimum_workers)
# if len(d) < minimum_workers then Exception
```

Essentially the call waits until it gets `limit` responses and returns.  If it doesn't get `limit` responses in 0.5 seconds then it returns with whatever it collected up until that point (so you still need to count the number of responses).  This allows for the response to come quicker than `timeout`, if possible.

**Comment by mwarkentin** [comment]
Someone should make a django-watchman-celery installable app that makes it super easy to do all of this. 😉
